import "./globals.css";
import ReactQueryProvider from "@/app/providers/ReactQueryProvider";
import {Inter as FontSans} from "next/font/google"
import { cn } from "@/lib/utils"

const fontSans = FontSans({
    subsets: ["latin"],
    variable: "--font-sans",
})

export const metadata = {
  title: "App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

    <html lang="en">
      <body className={cn("min-h-screen bg-background font-sans antialiased", fontSans.variable)}>
      <ReactQueryProvider>
      {children}
      </ReactQueryProvider>
      </body>
    </html>
  );
}
