services:
  backend:
    image: git-lab.ctif.md:4567/catalin.raebschi/backend:latest
    container_name: backend
    ports:
      - "8080:8080"
    networks:
      - network
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - network
  model:
    image: ollama/ollama
    restart: always
    volumes:
      - ollama_data:/app/data
    ports:
      - "11435:11434"
    networks:
      - network
networks:
  network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  ollama_data:
    driver: local
