version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network
  ollama:
    image: ollama/ollama
    container_name: my_ollama
    restart: always
    volumes:
      - ollama_data:/app/data
    ports:
      - "11435:11434"
    networks:
      - postgres_network
    command:
      - ollama run llama3.1
networks:
  postgres_network:
    driver: bridge


volumes:
  postgres_data:
  ollama_data:
    driver: local

