version: '3'
services:
  nextjs:
    image: git-lab.ctif.md:4567/catalin.raebschi/frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    command: ["pnpm", "start"]
    volumes:
      - .:/app
