services:
  frontend:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    volumes:
      - ./src:/app
    working_dir: /app
    command: ["pnpm", "run", "dev"]

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: my_backend
    ports:
      - "8080:8080"
    volumes:
        - ./backend:/app
    networks:
      - app_network
    depends_on:
      - postgres
      - ollama
    env_file:
      - secrets.env

  postgres:
    image: postgres:latest
    container_name: my_postgres
    restart: always
#    environment:
#      POSTGRES_DB: ${POSTGRES_DB}
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    env_file:
      - secrets.env

  ollama:
    image: ollama/ollama
    container_name: my_ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/app/data
    networks:
      - app_network
#    environment:
#      AI_OLLAMA_BASE_URL: ${AI_OLLAMA_BASE_URL}
#      AI_OLLAMA_CHAT_MODEL: ${AI_OLLAMA_CHAT_MODEL}
    env_file:
      - secrets.env

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
  ollama_data:
    driver: local
