services:
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runnerPSB
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/:/etc/gitlab-runner/