spring:
  docker:
    compose:
      enabled: true
  application:
    name: App
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
