import type { Metadata } from "next";
import { Inter as FontSans} from "next/font/google";
import "../styles/globals.css";

const inter = FontSans({ subsets: ["latin"] });
import { cn } from "@/lib/utils"

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})
export const metadata: Metadata = {
  title: "App",
  description: "Generated by create next app",
};

// @ts-ignore
export default function RootLayout({ children }: RootLayoutProps) {
  return (
      <html lang="en" suppressHydrationWarning>
      <head />
      <body
          className={cn(
              "min-h-screen bg-background font-sans antialiased",
              fontSans.variable
          )}
      >{children}</body>
    </html>
  );
}
