spring:
  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  ai:
    ollama:
      base-url: ${AI_OLLAMA_BASE_URL}
      chat:
        options:
          model: ${AI_OLLAMA_CHAT_MODEL}

  banner:
    location: ${SPRING_BANNER_LOCATION}

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driverClassName: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: ${SERVER_PORT}

springdoc:
  api-docs:
    path: ${SPRINGDOC_API_DOCS_PATH}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
